### PR TITLE
Work around for #6 and some more fixes

### PR DESCRIPTION
**Pull request by markruys**
Okay, this got a bit out of hand. Yes, I did implement a work around for #6. But actually I completely rewrote the Python scripts. So @FilipDem, you might not like this and refuse the PR. 

Hopefully I did not introduce too many bugs, but I did fix a few:

- Use Domoticz device description field to link to the Nest data (work around so now you can rename these devices in Domoticz)
- Restart plugin would silently crash the Nest class (caused by a ugly Python bug)
- Limit API requests to 10 seconds instead of infinite
- Ignore the \_\_pycache\_\_
- Retrieve where map instead of hard coding it
- Fix issue when in some occasions a unit conflict could occur
- Prevent error when commands are issued too fast by the user

Also:

- Added logging to the Nest class
- Added IMHO more sensible logging messages
- Use environment variable to test nest.py on the command line
- Set temperature resolution to 0.1° and humidity resolution to 1%
- Dump devices to log in debug mode
- Refactor code, make it more the Python way (I think)

### CODE REVIEW

**Comment by FilipDem** [comment]
Hi Mark,
I just took a quick look... and will investigate later more in detail. I installed your version already on a Domoticz test version. However when renaming a device (I changed the Temp/Hum), an error shows up:

`2020-11-07 10:48:31.550 Error: (TestNest) Device creation failed, Hardware/Unit combination (2:8) already exists in Domoticz.`

**Comment by FilipDem** [comment]
> Hi Mark,
> I just took a quick look... and will investigate later more in detail. I installed your version already on a Domoticz test version. However when renaming a device (I changed the Temp/Hum), an error shows up:
> 
> `2020-11-07 10:48:31.550 Error: (TestNest) Device creation failed, Hardware/Unit combination (2:8) already exists in Domoticz.`

Hi Mark, sorry, just saw that Domoticz was not restarted when having updated the plugin.py. Renaming works fine... However I saw that new devices are created at the startup meaning that all historical data is lost? Wouldn't it be possible to re-use the same units by default if they already exist?

**Comment by markruys** [comment]
> However I saw that new devices are created at the startup meaning that all historical data is lost? Wouldn't it be possible to re-use the same units by default if they already exist?

That's doable. Basically it means populating the description field with the name when description is empty (or missing the [...] tag).

I've just committed a repair for a fix which wasn't working properly.

**Comment by markruys** [comment]
> > However I saw that new devices are created at the startup meaning that all historical data is lost? Wouldn't it be possible to re-use the same units by default if they already exist?

I've just commited a change to convert the legacy mapping in the name field to the description field. In your case, please remove the newly created devices first (if you did not do this already).

**Comment by FilipDem** [comment]
Seems to work... Just one error... Seems you changed the name "Eco mode" to "Eco Mode", this one is still recreated. Could you make the (small) change to avoid this one also?
And some recommendations before I start merging:
- I see some left-overs from a previous copy/paste on line 66 (to delete) and line 502-205 (to replace by `pass`)
- Line 245... I would prefer this is replaced by a "Debug" message... It makes no added value to log systematically this information
- Line 358, idem but then replace the "Error" by "Debug" for the simple reason that errors are sent by mail to take action (eg when the credentials are expired). However no action is required here...

Thanks for your contribution Mark.
Let me know if the above if done (or if you wouldn't do it) before I merge...

**Comment by markruys** [comment]
Sure, I've implemented the changes you suggested. Thanks, Mark

**Comment by jupstra** [comment]
Guys, thanks for the good work. Maybe a noob question, but if I try to pull the new version, it says "error: Your local changes to the following files would be overwritten by merge: plugin.py" Is there way to update the new version without loosing my current devices/eg historical data in Domoticz? Many thanks!

**Comment by FilipDem** [comment]
Mark contributed and made it happen that the historical information is not lost when updating the plugin. And I confirm that it does.
So if you update from a previous version to this latest version, the data will be kept.

**Pull request merged**
